# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Details = QtWidgets.QTextEdit(self.centralwidget)
        self.Details.setGeometry(QtCore.QRect(40, 360, 361, 191))
        self.Details.setObjectName("Details")
        self.Summary = QtWidgets.QTextEdit(self.centralwidget)
        self.Summary.setGeometry(QtCore.QRect(420, 360, 371, 191))
        self.Summary.setObjectName("Summary")
        self.Type = QtWidgets.QComboBox(self.centralwidget)
        self.Type.setGeometry(QtCore.QRect(40, 30, 121, 22))
        self.Type.setObjectName("Type")
        self.Filter = QtWidgets.QTextEdit(self.centralwidget)
        self.Filter.setGeometry(QtCore.QRect(180, 30, 241, 21))
        self.Filter.setObjectName("Filter")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(460, 30, 75, 31))
        self.Start.setObjectName("Start")
        self.Plot = QtWidgets.QPushButton(self.centralwidget)
        self.Plot.setEnabled(False)
        self.Plot.setGeometry(QtCore.QRect(660, 30, 75, 31))
        self.Plot.setObjectName("Plot")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setEnabled(False)
        self.Stop.setGeometry(QtCore.QRect(560, 30, 75, 31))
        self.Stop.setObjectName("Stop")
        self.PackageList = QtWidgets.QTableView(self.centralwidget)
        self.PackageList.setGeometry(QtCore.QRect(40, 70, 751, 261))
        self.PackageList.setObjectName("PackageList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionseting = QtWidgets.QAction(MainWindow)
        self.actionseting.setObjectName("actionseting")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionsave_as)
        self.menu.addAction(self.actionseting)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start.setText(_translate("MainWindow", "启动"))
        self.Plot.setText(_translate("MainWindow", "统计数据"))
        self.Stop.setText(_translate("MainWindow", "清空"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionseting.setText(_translate("MainWindow", "seting"))
